# Generated by Django 4.1 on 2022-09-02 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0002_delete_entregable_delete_estudiante_delete_profesor'),
    ]

    operations = [
        migrations.CreateModel(
            name='clase1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var1', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='clase2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var2', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='clase3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('var3', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Curso',
        ),
    ]
