# Generated by Django 4.1 on 2022-09-06 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0004_staff_temas_usuarios_delete_clase1_delete_clase2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuarios',
            name='registro',
        ),
    ]
