# Generated by Django 4.1 on 2022-09-06 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppCoder', '0005_remove_usuarios_registro'),
    ]

    operations = [
        migrations.RenameField(
            model_name='temas',
            old_name='economia',
            new_name='tema_1',
        ),
        migrations.RenameField(
            model_name='temas',
            old_name='internet',
            new_name='tema_2',
        ),
        migrations.RenameField(
            model_name='temas',
            old_name='juegos',
            new_name='tema_3',
        ),
        migrations.RenameField(
            model_name='temas',
            old_name='naturaleza',
            new_name='tema_4',
        ),
        migrations.AddField(
            model_name='staff',
            name='email',
            field=models.EmailField(default='DEFAULT VALUE', max_length=254),
        ),
        migrations.AddField(
            model_name='staff',
            name='profesion',
            field=models.CharField(default='DEFAULT VALUE', max_length=50),
        ),
    ]
